### PR TITLE
Add messaging views

### PR DESCRIPTION
**Pull request by ElijahGeorge**
If this PR fixes a bug, you _must_ add test cases representative of the bug.

Please refer to [Tettra](https://app.tettra.co/teams/amida/pages/amida-pull-request-and-code-review-guide) for PR review guidelines.

#### What does this PR do?
Adds Messages/Threads View

#### Related JIRA tickets:
https://jira.amida-tech.com/browse/ORANGE-174

### CODE REVIEW

**Comment by puckybreg** [comment]
@ElijahGeorge Take a look at my refactor and tell me what you think. I have yet to tackle the ThreadsView but that will be next on the list. 
simulator screen shot - iphone 6 - 2018-02-06 at 19 18 52

**Comment by ElijahGeorge** [comment]
Nice @puckybreg !! Thanks for this

**Comment by B3rry** [comment]
It looks like this has been rebased, is that correct?

**Comment by puckybreg** [comment]
@B3rry Yes, we have merged develop into this branch at several stages to keep it up to date with changes happening in other branches.

**Pull request merged**
